# Generated by Django 5.2.12 on 2026-03-31 21:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('plans', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LifeArea',
            fields=[
                ('code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(default='circle', max_length=50)),
                ('scripture_tags', models.JSONField(default=list, help_text='Keywords that map to this area')),
                ('reflection_prompts', models.JSONField(default=list, help_text='Default prompts for this area')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Life Area',
                'verbose_name_plural': 'Life Areas',
                'db_table': 'life_areas',
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='UserJourney',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal_categories', models.JSONField(default=list)),
                ('goal_statement', models.TextField(help_text="User's own words describing their goal")),
                ('success_definition', models.TextField(help_text='What does success look like?')),
                ('focus_areas', models.JSONField(default=list, help_text='List of LifeArea codes')),
                ('encrypted_specific_struggle', models.BinaryField(blank=True, null=True)),
                ('reading_mode', models.CharField(choices=[('ai_suggested', 'AI Suggested'), ('self_directed', 'Self Directed'), ('hybrid', 'Hybrid')], default='hybrid', max_length=20)),
                ('custom_readings', models.JSONField(default=list)),
                ('current_day', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completion_reflection', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('next_journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_journey', to='reflections.userjourney')),
                ('reading_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='plans.readingplan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journeys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Journey',
                'verbose_name_plural': 'User Journeys',
                'db_table': 'user_journeys',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DailyReflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('scripture_reference', models.CharField(max_length=200)),
                ('scripture_themes', models.JSONField(default=list, help_text='AI-extracted themes')),
                ('encrypted_reflection', models.BinaryField(blank=True, null=True)),
                ('area_scores', models.JSONField(default=dict, help_text="Life area scores: {'integrity': 4, 'faith': 3}")),
                ('gratitude_note', models.TextField(blank=True)),
                ('struggle_note', models.TextField(blank=True)),
                ('tomorrow_intention', models.TextField(blank=True)),
                ('ai_insight', models.TextField(blank=True)),
                ('ai_provider_used', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reflections', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='reflections.userjourney')),
            ],
            options={
                'verbose_name': 'Daily Reflection',
                'verbose_name_plural': 'Daily Reflections',
                'db_table': 'daily_reflections',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('user', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AlignmentTrend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('week', 'Week'), ('month', 'Month')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('area_averages', models.JSONField(default=dict, help_text="Average scores: {'integrity': 3.5, 'faith': 4.2}")),
                ('area_deltas', models.JSONField(default=dict, help_text="Change from previous: {'integrity': 0.3, 'faith': -0.1}")),
                ('ai_summary', models.TextField(blank=True)),
                ('patterns', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alignment_trends', to=settings.AUTH_USER_MODEL)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alignment_trends', to='reflections.userjourney')),
            ],
            options={
                'verbose_name': 'Alignment Trend',
                'verbose_name_plural': 'Alignment Trends',
                'db_table': 'alignment_trends',
                'ordering': ['-period_start'],
                'unique_together': {('user', 'period_type', 'period_start')},
            },
        ),
    ]
