# Generated by Django 5.2.12 on 2026-03-31 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenThread',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('thread_type', models.CharField(choices=[('struggle', 'Struggle/Challenge'), ('commitment', 'Commitment Made'), ('question', 'Unanswered Question'), ('relationship', 'Relationship Issue'), ('decision', 'Pending Decision'), ('confession', 'Something Shared')], max_length=20)),
                ('encrypted_summary', models.BinaryField()),
                ('encrypted_original_context', models.BinaryField(blank=True, null=True)),
                ('related_life_area', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open - Active'), ('following_up', 'Following Up'), ('progressing', 'User Reports Progress'), ('resolved', 'Resolved'), ('deferred', 'User Chose to Defer'), ('dropped', 'User Chose to Drop')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_mentioned_at', models.DateTimeField(auto_now_add=True)),
                ('last_followup_at', models.DateTimeField(blank=True, null=True)),
                ('followup_after_days', models.PositiveIntegerField(default=3)),
                ('followup_count', models.PositiveIntegerField(default=0)),
                ('max_followups', models.PositiveIntegerField(default=3)),
                ('skip_count', models.PositiveIntegerField(default=0)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_resolution_note', models.BinaryField(blank=True, null=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='open_threads', to='reflections.userjourney')),
                ('source_reflection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detected_threads', to='reflections.dailyreflection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_threads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Open Thread',
                'verbose_name_plural': 'Open Threads',
                'db_table': 'open_threads',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_text', models.CharField(max_length=200)),
                ('response', models.CharField(blank=True, choices=[('better', 'Better'), ('same', 'Same'), ('worse', 'Worse'), ('yes', 'Yes'), ('no', 'No'), ('skipped', 'Skipped'), ('resolved', 'Resolved')], max_length=20, null=True)),
                ('expanded', models.BooleanField(default=False)),
                ('encrypted_expanded_response', models.BinaryField(blank=True, null=True)),
                ('shown_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('reflection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thread_prompts', to='reflections.dailyreflection')),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='reflections.openthread')),
            ],
            options={
                'verbose_name': 'Thread Prompt',
                'verbose_name_plural': 'Thread Prompts',
                'db_table': 'thread_prompts',
                'ordering': ['-shown_at'],
            },
        ),
    ]
