# Generated by Django 5.2.12 on 2026-04-01 02:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0002_openthread_threadprompt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusIntention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_type', models.CharField(choices=[('day', 'Daily'), ('week', 'Weekly'), ('month', 'Monthly')], max_length=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('encrypted_intention', models.BinaryField()),
                ('themes', models.JSONField(default=list, help_text='AI-extracted themes from intention')),
                ('related_life_areas', models.JSONField(default=list, help_text='Life area codes')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired')], default='active', max_length=20)),
                ('passages_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='focus_intentions', to='reflections.userjourney')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_intentions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Focus Intention',
                'verbose_name_plural': 'Focus Intentions',
                'db_table': 'focus_intentions',
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='DevotionalPassage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence_number', models.PositiveIntegerField(default=1)),
                ('scheduled_date', models.DateField()),
                ('scripture_reference', models.CharField(max_length=200)),
                ('scripture_text', models.TextField()),
                ('translation', models.CharField(default='NIV', max_length=20)),
                ('stylized_quote', models.TextField(help_text='Formatted quote for display')),
                ('context_note', models.TextField(blank=True, help_text='Historical/cultural context')),
                ('connection_to_focus', models.TextField(help_text="How this relates to user's focus")),
                ('reflection_prompts', models.JSONField(default=list, help_text='Questions for reflection')),
                ('application_suggestions', models.JSONField(default=list, help_text='Practical applications')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('encrypted_user_reflection', models.BinaryField(blank=True, null=True)),
                ('reflection_saved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devotional_passages', to=settings.AUTH_USER_MODEL)),
                ('focus_intention', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to='reflections.focusintention')),
            ],
            options={
                'verbose_name': 'Devotional Passage',
                'verbose_name_plural': 'Devotional Passages',
                'db_table': 'devotional_passages',
                'ordering': ['scheduled_date', 'sequence_number'],
                'unique_together': {('focus_intention', 'sequence_number')},
            },
        ),
    ]
