# Generated by Django 5.2.12 on 2026-04-03 04:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflections', '0003_focus_intentions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptureInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scripture_reference', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=20)),
                ('theme', models.CharField(blank=True, max_length=500, null=True)),
                ('focus_intention', models.CharField(blank=True, max_length=500, null=True)),
                ('focus_themes', models.JSONField(blank=True, default=list, null=True)),
                ('insight_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessed_at', models.DateTimeField(auto_now=True)),
                ('access_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scripture_insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'scripture_reference', 'translation', 'theme'], name='reflections_user_ref_idx'), models.Index(fields=['user', 'scripture_reference', 'focus_intention'], name='reflections_user_focus_idx')],
            },
        ),
    ]
