# Generated by Django 5.2.12 on 2026-04-01 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_base_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_provider',
            field=models.CharField(choices=[('none', 'None (Use System Default)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)'), ('openrouter', 'OpenRouter'), ('ollama', 'Ollama (Local)'), ('custom', 'Custom OpenAI-Compatible')], default='none', max_length=20),
        ),
    ]
