# Generated by Django 5.2.12 on 2026-03-31 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title_en', models.CharField(max_length=200)),
                ('title_es', models.CharField(blank=True, max_length=200)),
                ('description_en', models.TextField()),
                ('description_es', models.TextField(blank=True)),
                ('duration_days', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('general', 'General'), ('fatherhood', 'Fatherhood'), ('leadership', 'Leadership'), ('recovery', 'Recovery'), ('marriage', 'Marriage'), ('faith', 'Faith Foundations')], default='general', max_length=20)),
                ('is_premium', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reading_plans',
            },
        ),
        migrations.CreateModel(
            name='ReadingPlanDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('passages', models.JSONField(help_text='List of passage references')),
                ('theme_en', models.CharField(blank=True, max_length=200)),
                ('theme_es', models.CharField(blank=True, max_length=200)),
                ('reflection_prompts_seed', models.TextField(blank=True, help_text='Seed prompt for LLM generation')),
            ],
            options={
                'db_table': 'reading_plan_days',
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='UserPlanEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('current_day', models.PositiveIntegerField(default=1)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_plan_enrollments',
            },
        ),
    ]
