# Generated by Django 5.2.12 on 2026-03-31 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0)),
                ('longest_streak', models.PositiveIntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('total_entries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'user_streaks',
            },
        ),
    ]
