# Generated by Django 5.2.12 on 2026-03-31 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Spanish')], max_length=2)),
                ('is_public_domain', models.BooleanField(default=True)),
                ('provider_class', models.CharField(blank=True, help_text='Dotted path to Python class for API-based translations', max_length=200)),
            ],
            options={
                'db_table': 'bible_translations',
            },
        ),
        migrations.CreateModel(
            name='BibleVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=10)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.PositiveIntegerField()),
                ('verse', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verses', to='bible.bibletranslation')),
            ],
            options={
                'db_table': 'bible_verses',
                'indexes': [models.Index(fields=['translation', 'book', 'chapter'], name='bible_verse_transla_a445b6_idx'), models.Index(fields=['book', 'chapter', 'verse'], name='bible_verse_book_7fdc1f_idx')],
                'unique_together': {('translation', 'book', 'chapter', 'verse')},
            },
        ),
    ]
