# Generated by Django 5.2.12 on 2026-04-01 06:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bible', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VerseHighlight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('book', models.CharField(max_length=50)),
                ('chapter', models.IntegerField()),
                ('verse_start', models.IntegerField()),
                ('verse_end', models.IntegerField(blank=True, null=True)),
                ('translation', models.CharField(default='KJV', max_length=20)),
                ('color', models.CharField(choices=[('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('pink', 'Pink'), ('orange', 'Orange')], default='yellow', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verse_highlights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verse_highlights',
                'ordering': ['book', 'chapter', 'verse_start'],
                'unique_together': {('user', 'book', 'chapter', 'verse_start', 'translation')},
            },
        ),
    ]
