# Generated by Django 5.2.12 on 2026-03-31 11:43

import apps.groups.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('invite_code', models.CharField(default=apps.groups.models.generate_invite_code, max_length=8, unique=True)),
                ('max_members', models.PositiveIntegerField(default=25)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('church', 'Church')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.CreateModel(
            name='GroupEngagementSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_members', models.PositiveIntegerField()),
                ('members_active_today', models.PositiveIntegerField()),
                ('avg_streak', models.FloatField(default=0.0)),
                ('plan_completion_pct', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'group_engagement_snapshots',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('leader', 'Leader'), ('admin', 'Admin')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'group_memberships',
            },
        ),
    ]
