# Generated by Django 5.2.12 on 2026-03-31 11:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('encrypted_content', models.BinaryField()),
                ('reflection_prompts_used', models.JSONField(blank=True, default=list)),
                ('mood_tag', models.CharField(blank=True, choices=[('grateful', 'Grateful'), ('struggling', 'Struggling'), ('convicted', 'Convicted'), ('peaceful', 'Peaceful'), ('fired_up', 'Fired Up')], max_length=20)),
                ('is_private', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
