# Generated by Django 5.2.13 on 2026-04-13 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExplorationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_input', models.TextField(help_text='The freeform text the user submitted')),
                ('summary', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='general', max_length=30)),
                ('passages', models.JSONField(default=list, help_text='Hydrated passage objects with reference, text, and reason')),
                ('prompts', models.JSONField(default=list, help_text='AI-generated reflection prompts')),
                ('plans', models.JSONField(default=list, help_text='Recommended reading plans at the time of search')),
                ('is_bookmarked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='explorations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exploration_history',
                'ordering': ['-created_at'],
            },
        ),
    ]
